kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
- ../../bases/generic-web-app

commonLabels:
  app.kubernetes.io/name: web-app-3

commonAnnotations:
  app.kubernetes.io/owner: some-team-3

namePrefix: web-app-3-

patches:
- ./patches/patch-deploy-replicas.yaml

images:
- name: container-image
  newName: stefanprodan/podinfo
  newTag: latest
