kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
- ../../bases/generic-web-app

commonLabels:
  app.kubernetes.io/name: web-app-1

commonAnnotations:
  app.kubernetes.io/owner: some-team
  flux.weave.works/automated: "true"
  flux.weave.works/tag.container-name: 'semver: ~0.0'
 
namePrefix: web-app-1-

#patches:
#- deploy-patch.yaml

images:
- name: container-image
  newName: nabadger/podinfo
  newTag: 0.0.2
