kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
- ../../bases/generic-web-app

commonLabels:
  app.kubernetes.io/name: web-app-1

commonAnnotations:
  app.kubernetes.io/owner: some-team

namePrefix: web-app-1-

images:
- name: container-image
  newName: nabadger/podinfo
  newTag: 0.0.1
