kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
- ../../bases/generic-web-app

commonLabels:
  app.kubernetes.io/name: web-app-2

commonAnnotations:
  app.kubernetes.io/owner: some-team-2

namePrefix: web-app-2-

images:
- name: container-image
  newName: stefanprodan/podinfo
  newTag: latest
