apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flux
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flux
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io.port: "3031"
      labels:
        name: flux
    spec:
      containers:
      - args:
        - --memcached-service=
        - --ssh-keygen-dir=/var/fluxd/keygen
        - --git-url=git@github.com:nabadger/flux-kustomize-example.git
        - --git-branch=test-policy-set
        - --git-path=environments/dev
        - --listen-metrics=:3031
        - --sync-interval=2m
        - --git-poll-interval=2m
        - --registry-poll-interval=1m
        image: docker.io/2opremio/flux:generators-releasers-bb344048
        imagePullPolicy: IfNotPresent
        name: flux
        ports:
        - containerPort: 3030
          protocol: TCP
        resources:
          requests:
            cpu: 150m
            memory: 128Mi
        volumeMounts:
        - mountPath: /var/fluxd/keygen
          name: git-keygen
      dnsPolicy: ClusterFirst
      serviceAccount: flux
      serviceAccountName: flux
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
        name: git-keygen
