apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - name: container-name
        ports:
        - containerPort: 8001
          name: metrics
