apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  env: dev
  flux.weave.works/automated: 'true'
  flux.weave.works/tag.container-name: semver:~0.0

bases:
- ../../overlays/web-app01
- ../../overlays/web-app02
